pool:
  vmImage: 'windows-latest'
steps:
- script: dotnet build App.sln
  displayName: 'dotnet build'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Cloud'
    organization: '2006-jun15-net'
    scannerMode: 'MSBuild'
    projectKey: 'quentin-project1'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    projects: ./*.sln
    publishWebProjects: true
  displayName: 'dotnet publish'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(27d24e29-5de1-40f6-85cf-709127ec138a)'
    appType: 'webApp'
    WebAppName: 'xfilgh'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    modifyOutputPath: true
    zipAfterPublish: true
  displayName: 'deploy'
